Repository magickasoft/food-paradise, pull requests merged in 2025-09, with the labels that each got.

#20 Feature/#16
  src/components/Cards/DetailCard.tsx
  src/components/Cards/RecipeCard.tsx
  src/components/DetailsTitle.tsx
  src/components/Header.tsx
  src/components/PageWrapper.tsx
  src/components/PopularCategories/PopularCategories.tsx
  src/components/RecipePage/AnotherRecipesBlock.tsx
  src/components/RecipePage/HeaderBlock.tsx
  src/components/RecipePage/RecipePage.tsx
  src/components/RecipePage/TipsBlock.tsx
  src/components/RecipePage/VariationsBlock.tsx
  src/components/SeasonalCategories/SeasonalCategories.tsx
  src/components/TipsList.tsx
  src/components/VariationsList.tsx
  src/components/styled-components/global-style.ts
  src/constants/recipes/dinner.ts
  src/constants/recipes/grill.ts
  src/constants/recipes/healthy.ts
  src/constants/recipes/salads.ts
  src/constants/recipes/snacks.ts
  src/constants/recipes/supper.ts
Labels: Review effort 3/5

#21 update yandex-verification
  bun.lockb
  package.json
  src/app/[locale]/layout.tsx
Labels: Review effort 1/5

#23 yandex-verification
  src/app/[locale]/layout.tsx
Labels: Review effort 1/5

#27 fix logic
  public/static/logo.png
  src/app/[locale]/layout.tsx
  src/components/Header.tsx
  src/constants/recipes/breakfast.ts
  src/constants/recipes/dessert.ts
  src/constants/recipes/dinner.ts
  src/constants/recipes/grill.ts
  src/constants/recipes/healthy.ts
  src/constants/recipes/refreshingDrinks.ts
  src/constants/recipes/salads.ts
  src/constants/recipes/snacks.ts
  src/constants/recipes/supper.ts
Labels: Review effort 2/5

#29 fix
  src/app/[locale]/layout.tsx
Labels: Review effort 1/5

#33 log env
  src/app/robots.ts
  src/app/sitemap.ts
  src/variables/domain.ts
  src/variables/url.ts
Labels: Review effort 2/5

#35 Update routing.ts
  src/i18n/routing.ts
Labels: Review effort 2/5

#36 pathnames
  src/app/sitemap.ts
  src/i18n/constants.ts
  src/i18n/createLocalizedPaths.ts
  src/i18n/routing.ts
Labels: Review effort 2/5

#37 Update routing.ts
  src/i18n/routing.ts
Labels: Review effort 1/5

#39 sitemap
  src/app/sitemap.ts
  src/i18n/createEntity.ts
  src/i18n/createLanguages.ts
Labels: Review effort 2/5
